### ISSUE TITLE
LICENSE file still says "Copyright (C) 2015 Antelle"

### ISSUE THREAD

**Issue by FreedomFighterSparrow** [kee-org/keevault#1]
I believe this was copied verbatim from keeweb and should be changed.

**Comment by luckyrat** [comment]
That's correct. Antelle still holds copyright over the parts of Kee Vault that were included from KeeWeb (technically the copyright is actually shared among many contributors but it's never practical for such subtleties to be defined in a license - nothing written in the license can actually change who owns the copyright of each part of code anyway).

The top of the LICENSE file states the copyright for the bulk of the Kee Vault project but KeeWeb's MIT license requires that the original copyright notice is retained while any code from that project is included within Kee Vault (which is only fair IMHO).

**Comment by FreedomFighterSparrow** [comment]
Good point! I need to brush up on my licenses. Thanks for the very complete answer :100:
