### ISSUE TITLE
Asus router, basic authentication, infinite Kee popups leads to Firefox crash

### ISSUE THREAD

**Issue by kulmegil** [kee-org/keevault#10]
Whenever user was logged into Asus router and their login expired.

Router keeps pooling status updates every 2-3 seconds but now  each XHR is creating Kee authentication popup.
This creates hundreds of popups in just few minutes and Firefox crash in results.
(and since each popup is a Firefox  window - it's pretty resource intense)

**Steps To Reproduce**
1. Login to Asus router
2. Leave tab open
3. Wait for login to expire
OR
4. Browser is restarted and last session is restored
(this defeats situation when user set option to never auto logout in router options)

**Expected behavior**
Just like native Firefox authentication popup, only one should be created for authentication for each website (or tab).

**Screenshots**
![crash](https://user-images.githubusercontent.com/570575/121101293-db9ab500-c7fb-11eb-9abd-09a4c35f16f9.png)
BONUS: every new popup duplicates login option
![crash2](https://user-images.githubusercontent.com/570575/121103373-1d2d5f00-c800-11eb-94d4-1a4730b22d87.png)

**Environment**
Kee v3.9.5
Firefox 91.0a1
Windows 10 18363

**Kdbx File**
Any database file that contains at least one matching entry 
(otherwise native Firefox modal popup will show)

**Logs**
Browser crashes, sometimes along with another app if computer runs out of RAM.

**Comment by luckyrat** [comment]
This is being discussed on the forum (not sure if you are already one of the participants @kulmegil ). In any case, it's not an issue specific to Kee Vault so I'm closing it.

https://forum.kee.pm/t/infinite-loop-of-popup-http-basic-auth-windows-created-session-restore/3710
